service: backend-endsls
app: ordering-dashboard
org: stucodegreen

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
  enviroment:
    PRODUCT_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:UpdateItem
      Resource: '*'

resources:
  Resources:
    ProductsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolocy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: 'id'
          - AttributeType: 'S'
        KeySchema:
          - AtributeName: 'id'
            KeyType: 'HASH'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: 'NEW_AND_OLD_IMAGES'
        TableName: ${self:provider.enviroment.PRODUCT_TABLE}
